# -*- coding: utf-8 -*-
"""har.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XCMQR3LJtkfLkXgO3rmJaSyyZSeVxVz8
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import matplotlib
import tensorflow as tf
from sklearn import metrics
import os

# defining input signals and the labels for activities associated.
input_metrics = ["x_acceleration",
                 "y_acceleration",
                 "z_acceleration",
                 "x_gyro",
                 "y_gyro",
                 "z_gyro",
                 "total_x_acceleration",
                 "total_y_acceleration",
                 "total_z_acceleration"]
labels = ["Walking",
          "Upstairs",
          "Downstairs",
          "Sitting",
          "Standing",
          "Laying"]

dataset_path = "/content/drive/My Drive/UCI HAR Dataset"

Training = dataset_path+"/train"
Testing = dataset_path+"/test"

#Feature extraction
features = list()
with open(dataset_path + "/features.txt") as feature:
    for x in feature:
        features.append(x.split()[1])
ft_df = pd.DataFrame(features)
ft_df.head()

ft_df.tail()

train_df = pd.read_csv(dataset_path+"/train/X_train.txt",delim_whitespace=1,names = features)

train_df.head()

train_df.plot(legend=False,ylim=(0,1),xlim=(0,5),figsize=(30,5))

'''
train_df["subject"] = pd.read_csv(Training+"/subject_train.txt",header = None, squeeze = True)
train_df["activity"] = pd.read_csv(Training+"/y_train.txt", header = None, squeeze = True)
activity = pd.read_csv(Training+"/y_train.txt", header = None, squeeze = True)
labels = 
train_df["subject"].head()
'''

